### ISSUE TITLE
eslint 1.8 new rules

### ISSUE THREAD

**Issue by AdriVanHoudt** [continuationlabs/eslint-config-hapi#23]
The rules added with 1.8 seem useful to add
also `no-shadow` now has an `allow` option see http://eslint.org/docs/rules/no-shadow#allow which can replace https://www.npmjs.com/package/no-shadow-relaxed if I am correct

**Comment by cjihrig** [comment]
ESLint 1.8 introduced these rules:

- `arrow-body-style` - I originally wanted to use this rule, set to `"always"`, but we decided to allow implicit returns. The other setting is `"as-needed"`, but I don't see much use for this. I talked to @hueniverse about it and it was decided that single line arrow functions can still be implemented as a normal function if you so choose. So, this rule is not much help.
- `no-arrow-condition` - This rule helps catch typos and bad practices, so I'm +1 for enabling this rule.

As for the new `no-shadow` vs `no-shadow-relaxed`, I'll leave that call up to @geek, as he wrote `no-shadow-relaxed`.

**Comment by AdriVanHoudt** [comment]
cool, will wait for @geek and then let me know if you want a PR or you prefer doing it yourself ;)

**Comment by cjihrig** [comment]
PRs are welcome. The config is in `lib/index.js`. Each changed rule gets a test in `test/index.js` based on a fixture in `test/fixtures/{rule-name}.js`. The test does not need to be comprehensive for the rule (that testing should be done in the rule itself).

**Comment by AdriVanHoudt** [comment]
ok will wait for @geek then ;)

**Comment by geek** [comment]
@AdriVanHoudt good call, looks like we can switch to the new rule option.

**Comment by AdriVanHoudt** [comment]
@cjihrig unless you need it quicker I can only do a pr by end of the week

**Comment by cjihrig** [comment]
- Added `no-arrow-condition` rule in e7296ffd32b952591bd7e932bfad65906adacbef.
- Replaced `no-shadow-relaxed` with `no-shadow` in 9cde7d91c6de357dd64db693471d9db2bbae451c.

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by AdriVanHoudt** [comment]
any eta on :shipit: ?

**Comment by cjihrig** [comment]
v6.0.0 has shipped. The lab PR is https://github.com/hapijs/lab/pull/480
