### ISSUE TITLE
Add an ES5 compatible config?

### ISSUE THREAD

**Issue by pdehaan** [continuationlabs/eslint-config-hapi#24]
We love your custom config, but many of our projects still use ES5, so we have to extend the **eslint-config-hapi** config and then disable ES6-specific rules (specifically `prefer-arrow-callback` and `no-var` -- although we'd have to adjust in the future if new ES6 rules were added to your config).

Not sure if you want to add another shared config which extends your base config (lib/index.js) and overrides/disables ES6 specific rules. That way we could simply do `extends: hapi/es5`.

**Comment by cjihrig** [comment]
I'm open to this, although it looks like you already addressed it in your project.

**Comment by arb** [comment]
Is using a previous version a possibility?

**Comment by cjihrig** [comment]
Using a previous version is a quick fix, but not really a long term solution if you're stuck on ES5, as ESLint is always coming out with new rules that you might want to use.

**Comment by cjihrig** [comment]
Fixed in 40d0311bea5fef2b8ed898d487cbc032b16d2dc3. Published in v6.1.0
