### ISSUE TITLE
Module import capitalisation isn't enforced

### ISSUE THREAD

**Issue by prashaantt** [continuationlabs/eslint-config-hapi#29]
I'm wondering why `hapi-capitalize-modules` [isn't strictly enforced](https://github.com/continuationlabs/eslint-config-hapi/blob/master/lib/index.js#L29), even though the [Hapi style guide](http://hapijs.com/styleguide#user-content-require) isn't ambivalent on this rule.

**Comment by cjihrig** [comment]
This is a wider issue than just `hapi-capitalize-modules`. There don't seem to be any rules for what generates a warning and what generates an error. IMO, we should just use error level throughout. I started this from a config file that was in lab. Maybe @geek can shed some light/feedback on this?

**Comment by geek** [comment]
@cjihrig I would like to error on this as well

**Comment by prashaantt** [comment]
I can submit a tiny PR for this. Just to be clear, going full throttle on this would mean it should apply everywhere and not just on `global-scope-only`, correct?

**Comment by cjihrig** [comment]
@geek how would you feel about having all enforced rules have a severity of 2 (error). I don't really see a point to having warning level linting rules, since we pretty much treat them as errors.

@prashaantt no, we should still only enforce this on the global scope. See https://github.com/hapijs/lab/pull/368#discussion_r31950100. I thought your question had to do with rule severity.

**Comment by prashaantt** [comment]
@cjihrig With `global-scope-only` I seem to be getting no warnings for any scope at all. I can only get this to actually lint by removing the global scope option. I'll try writing a test to show what I mean.

**Comment by AdriVanHoudt** [comment]
Seems like these rules should be errors and Lab linting should only fail if there are errors not when there are only warnings? (just a thought)

**Comment by cjihrig** [comment]
@prashaantt the problem you're seeing with `global-scope-only` came from a breaking change in [ESLint 1.4.0](http://eslint.org/blog/2015/09/eslint-v1.4.0-released/). My guess would be https://github.com/eslint/eslint/issues/3700 specifically.

**Comment by cjihrig** [comment]
Published hapi-capitalize-modules@1.1.4 with the fix. Added a regression test in this module in #30.

**Comment by cjihrig** [comment]
Published v8.0.1 everything should automatically get picked up by lab.

**Comment by prashaantt** [comment]
@cjihrig Thanks, works as expected now.
