### ISSUE TITLE
Update eqeqeq rule

### ISSUE THREAD

**Issue by arb** [continuationlabs/eslint-config-hapi#34]
I'd like to propose adding "allow-null" to the [eqeqeq rule](http://eslint.org/docs/rules/eqeqeq#allow-null). This would allow for checks for values of `null` or `undefined` to be done like:

```
function (value) {
  if (value == null) {
    console.log('value is null or undefined');
  }
```

While it's generally not a great idea to let JS do whatever it wants during coercion, in this one instance, I think the trade off is worth it as checking `== null` is a pretty common and understood pattern.

**Comment by AdriVanHoudt** [comment]
why not `if (!value)` or `if (value === null || value === undefined)` ?

**Comment by cjihrig** [comment]
`if (!value)` is not strictly equivalent.

I'm personally -1 on this, but it doesn't really matter anyway. This would have to get cleared in the hapi style guide.

**Comment by arb** [comment]
Why are you -1 on this? I agree though, this would have to go up the ladder.

**Comment by cjihrig** [comment]
I don't like it because it is more consistent to just use `===` everywhere. This one exception only saves you a few characters. I think `foo === undefined || foo === null` is faster too.

**Comment by cjihrig** [comment]
How about taking this up with the style guide (in hapijs/contrib I think), and if it gets OKed, I'll reopen this.
