### ISSUE TITLE
2.9.0 rules

### ISSUE THREAD

**Issue by AdriVanHoudt** [continuationlabs/eslint-config-hapi#37]
Any thoughts on the new rules from 2.9? 
* http://eslint.org/docs/rules/no-unsafe-finally
* http://eslint.org/docs/rules/no-useless-computed-key

Both seems fine to enable?

**Comment by cjihrig** [comment]
Yea, these both make sense to me.

**Comment by AdriVanHoudt** [comment]
Want a PR?

**Comment by cjihrig** [comment]
Sure. I'm not going to make a new release until https://github.com/hapijs/contrib/issues/83 is resolved, but no harm PRing these right now.

**Comment by cjihrig** [comment]
Closed in 9a91980ace00d3cd28f4add7aa0c54b4d170f07a
