### ISSUE TITLE
Make  { a: a } a violation

### ISSUE THREAD

**Issue by hueniverse** [continuationlabs/eslint-config-hapi#40]
Require `{ a }`

**Comment by cjihrig** [comment]
This can be done using the [object-shorthand](http://eslint.org/docs/rules/object-shorthand) rule with the `'properties'` setting. The same rule can be used to force this:

```js
const foo = {
    a: function() {},
    b: function() {}
};
```

to be written as:

```js
const foo = {
    a() {},
    b() {}
};
```

Interested in this, or just the properties?

**Comment by hueniverse** [comment]
Just the properties. The function shorthand is less readable.

**Comment by cjihrig** [comment]
As of ESLint 3.2.2, it doesn't look like it's possible to enforce the properties and prohibit functions at the same time (if anyone know of a way, a PR is welcome).

**Comment by hueniverse** [comment]
No need to prohibit the function, just don't force them.
