### ISSUE TITLE
Catch undeclared variables

### ISSUE THREAD

**Issue by sfabriece** [continuationlabs/eslint-config-hapi#45]
If I create a funtion on a non declared variable, I don't get an error. 
Is it possible to add for that?

**Comment by cjihrig** [comment]
@geek, it looks like the [`no-undef`](http://eslint.org/docs/rules/no-undef) rule has been turned off since I originally split this out of lab. Any idea why? If there isn't a good reason, I think we should try turning it on, with the `{ "typeof": false }` option set.

**Comment by geek** [comment]
@cjihrig I don't see a reason to keep it off, maybe it was just a bad copy-paste

**Comment by cjihrig** [comment]
OK. Well @sfabriece would you care to make a PR :-)

**Comment by cjihrig** [comment]
Closed via #47
