### ISSUE TITLE
unused-variable improvement

### ISSUE THREAD

**Issue by danielb2** [continuationlabs/eslint-config-hapi#5]
Would be nice if the unused variables weren't checked for as part of function arguments, i.e.

``` javascript
Wreck.get('https://google.com/', function (err, res, payload) {
    /* do stuff */
});
```

Here I will use `err` and `payload`, but the `res` which I have no choice but to add since the function signature shows up this way, will still be reported.  This is annoying if I can't do anything about it.

Function signatures should be ignored because you'll want to show what was passed.

**Comment by cjihrig** [comment]
This change has already been made in v3.0.1. See https://github.com/hapijs/lab/issues/453 for the discussion.

**Comment by danielb2** [comment]
ah, perfect :)
