### ISSUE TITLE
Brace style

### ISSUE THREAD

**Issue by AdriVanHoudt** [continuationlabs/eslint-config-hapi#6]
I recently added `"brace-style": [2, "stroustrup"]` to my setup but if I am correct this is also the hapi style no?

**Comment by cjihrig** [comment]
I believe you're correct. Not sure if this is something we want to enforce or not. @geek thoughts? For reference - http://eslint.org/docs/rules/brace-style

**Comment by AdriVanHoudt** [comment]
see https://github.com/hapijs/contrib/blob/master/Style.md#newlines

**Comment by cjihrig** [comment]
> I believe you're correct.

If @geek +1s this, I can enable it in this repo. It would constitute a major version bump in `eslint-config-hapi`, which is fine. However, it would also constitute a major bump in `lab`, which I think should be avoided right now, as v6 just recently came out. We don't want to overwhelm people with breaking changes related to linting.

**Comment by AdriVanHoudt** [comment]
every new rule here would be a major in lab, you could already implement it and then wait on more changes or something before doing a release?

**Comment by geek** [comment]
ya, go ahead and make the change... I will wait to release

**Comment by AdriVanHoudt** [comment]
:shipit:
