### ISSUE TITLE
Add test for duplicate lint entries

### ISSUE THREAD

**Issue by cjihrig** [continuationlabs/eslint-config-hapi#9]
#8 removed a duplicated rule in the config. We should have a test that loops over the keys in the config to make sure there are no duplicates.

**Comment by AdriVanHoudt** [comment]
how would you do this, the moment you require it it will just take the last occurrence of the key

**Comment by AdriVanHoudt** [comment]
some low level `read line by line` could work 
http://stackoverflow.com/questions/6156501/read-a-file-one-line-at-a-time-in-node-js/32599033#32599033

**Comment by cjihrig** [comment]
The config is just a couple of objects. Just loop over the keys and maintain a list of already seen keys.

**Comment by AdriVanHoudt** [comment]
the problem, as stated in first comment, is that when requiring, js will remove dupe keys and just assign the last value to it, so you will never have dupe keys
![](http://puu.sh/kL4jO/bd2fdbe90c.png)

**Comment by cjihrig** [comment]
Oh, duh you're right. Yea, you would have to do it at the source code level.

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by cjihrig** [comment]
On second thought, this might be overkill. Closing.

**Comment by AdriVanHoudt** [comment]
yeah maybe, it is probably more sane to just go through it once and then keep it in mind for future updates

**Comment by cjihrig** [comment]
Conveniently, this is taken care of now, as of 7e7117398e7a4e1460d6739e2b9deb5281fdad31

**Comment by AdriVanHoudt** [comment]
I feel dumb now haha also are you linting a linting config? meta

**Comment by cjihrig** [comment]
Yes. lintception

**Comment by AdriVanHoudt** [comment]
and belly button uses lab which uses this === infinite dependency :O
